// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSharp.Entity;

#nullable disable

namespace Liuliu.Demo.Web.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20250325085634_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("OSharp.Hosting.MultiTenancy.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasComment("编号");

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasComment("连接字符串");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<string>("CustomJson")
                        .HasColumnType("TEXT")
                        .HasComment("自定义配置数据");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT")
                        .HasComment("DeletedTime");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("TEXT")
                        .HasComment("到期时间");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("租户主机");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasComment("是否启用");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("租户名称");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("租户简称");

                    b.Property<string>("TenantKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("租户标识");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("TEXT")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("MultiTenancy_Tenant", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
