// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSharp.Entity;

#nullable disable

namespace Liuliu.Demo.Web.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
    [Migration("20221116015548_Init")]
    partial class Init
========
    [Migration("20250303081408_init")]
    partial class init
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                .HasAnnotation("ProductVersion", "6.0.11")
========
                .HasAnnotation("ProductVersion", "6.0.36")
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.EntityRole", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("FilterGroupJson")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("数据编号");

                    b.Property<string>("FilterGroupJson")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("过滤条件组Json字符串");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

                    b.Property<int>("Operation")
                        .HasColumnType("int")
                        .HasComment("数据权限操作");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasComment("角色编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("EntityId", "RoleId", "Operation")
                        .IsUnique()
                        .HasDatabaseName("EntityRoleIndex");

                    b.ToTable("Auth_EntityRole", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.EntityUser", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("FilterGroupJson")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("数据编号");

                    b.Property<string>("FilterGroupJson")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("过滤条件组Json字符串");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityId", "UserId")
                        .HasDatabaseName("EntityUserIndex");

                    b.ToTable("Auth_EntityUser", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.Module", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("编号");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("模块代码");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("模块名称");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<double>("OrderCode")
                        .HasColumnType("float")
                        .HasComment("排序码");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TreePathString")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");
========
                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasComment("父模块编号");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("模块描述");

                    b.Property<string>("TreePathString")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("父节点树形路径");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Auth_Module", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.ModuleFunction", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("FunctionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");

                    b.Property<Guid>("FunctionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("功能编号");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasComment("模块编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("ModuleId", "FunctionId")
                        .IsUnique()
                        .HasDatabaseName("ModuleFunctionIndex");

                    b.ToTable("Auth_ModuleFunction", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.ModuleRole", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasComment("模块编号");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasComment("角色编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ModuleId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ModuleRoleIndex");

                    b.ToTable("Auth_ModuleRole", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.ModuleUser", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit")
                        .HasComment("Disabled");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasComment("模块编号");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ModuleId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ModuleUserIndex");

                    b.ToTable("Auth_ModuleUser", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.LoginLog", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("登录IP");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2")
                        .HasComment("退出时间");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户代理头");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Identity_LoginLog", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.Organization", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("编号");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名称");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");
========
                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasComment("父组织机构编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("描述");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Identity_Organization", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.Role", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("编号");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("版本标识");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasComment("DeletedTime");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasComment("是否管理员角色");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasComment("是否默认角色");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasComment("是否系统角色");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("角色名称");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标准化角色名称");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("角色描述");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("NormalizedName", "DeletedTime")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[DeletedTime] IS NOT NULL");

                    b.ToTable("Identity_Role", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.RoleClaim", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("编号");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("声明类型");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("声明值");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasComment("角色编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Identity_RoleClaim", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.User", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("编号");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasComment("登录失败次数");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(500)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(500)");
========
                        .HasColumnType("nvarchar(500)")
                        .HasComment("版本标识");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasComment("DeletedTime");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("电子邮箱");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasComment("电子邮箱确认");

                    b.Property<string>("HeadImg")
                        .HasMaxLength(1000)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(1000)");
========
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("用户头像");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasComment("是否系统用户");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasComment("是否登录锁");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasComment("锁定时间");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("NickName")
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizeEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("用户昵称");

                    b.Property<string>("NormalizeEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标准化的电子邮箱");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("标准化的用户名");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("密码哈希值");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("手机号码");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasComment("手机号码确定");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(500)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(500)");
========
                        .HasColumnType("nvarchar(500)")
                        .HasComment("安全标识");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasComment("双因子身份验证");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("用户名");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("NormalizeEmail", "DeletedTime")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName", "DeletedTime")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[DeletedTime] IS NOT NULL");

                    b.ToTable("Identity_User", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserClaim", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("编号");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(500)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                        .HasColumnType("nvarchar(500)")
                        .HasComment("声明类型");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("声明值");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Identity_UserClaim", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserDetail", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("编号");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("RegisterIp")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("注册IP");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Identity_UserDetail", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserLogin", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Avatar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");

                    b.Property<string>("Avatar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("第三方用户头像");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("登录的登录提供程序");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("第三方用户昵称");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("第三方用户的唯一标识");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LoginProvider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("UserLoginIndex")
                        .HasFilter("[LoginProvider] IS NOT NULL AND [ProviderKey] IS NOT NULL");

                    b.ToTable("Identity_UserLogin", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserRole", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasComment("DeletedTime");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasComment("角色编号");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId", "DeletedTime")
                        .IsUnique()
                        .HasDatabaseName("UserRoleIndex")
                        .HasFilter("[DeletedTime] IS NOT NULL");

                    b.ToTable("Identity_UserRole", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserToken", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("登录提供者");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("令牌名称");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("用户编号");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("令牌值");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoginProvider", "Name")
                        .IsUnique()
                        .HasDatabaseName("UserTokenIndex")
                        .HasFilter("[LoginProvider] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("Identity_UserToken", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.Message", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("datetime2")
                        .HasComment("生效时间");

                    b.Property<bool>("CanReply")
                        .HasColumnType("bit")
                        .HasComment("是否允许回复");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("内容");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasComment("删除时间");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("过期时间");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

                    b.Property<bool>("IsSended")
                        .HasColumnType("bit")
                        .HasComment("是否发送");

                    b.Property<int>("MessageType")
                        .HasColumnType("int")
                        .HasComment("消息类型");

                    b.Property<int>("NewReplyCount")
                        .HasColumnType("int")
                        .HasComment("新回复数");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasComment("发送人编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("标题");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Infos_Message", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.MessageReceive", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("接收的主消息编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<int>("NewReplyCount")
                        .HasColumnType("int")
                        .HasComment("新回复数，接收者使用");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2")
                        .HasComment("接收时间");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("消息接收人编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("Infos_MessageReceive", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.MessageReply", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BelongMessageId")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");

                    b.Property<Guid>("BelongMessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("回复所属主消息，用于避免递归查询");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("消息内容");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasComment("删除时间");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasComment("是否已读");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("ParentMessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentReplyId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("ParentMessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("回复的主消息，当回复主消息时有效");

                    b.Property<Guid>("ParentReplyId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("回复的回复消息，当回复回复消息时有效");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment(" 消息回复人编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("BelongMessageId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("ParentReplyId");

                    b.HasIndex("UserId");

                    b.ToTable("Infos_MessageReply", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Systems.Entities.AuditEntity", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("EntityKey")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("EntityKey");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Name");

                    b.Property<int>("OperateType")
                        .HasColumnType("int")
                        .HasComment("OperateType");

<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("OperationId")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("OperationId");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("TypeName");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("Systems_AuditEntity", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Systems.Entities.AuditOperation", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Browser");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("CreatedTime");

                    b.Property<int>("Elapsed")
                        .HasColumnType("int")
                        .HasComment("Elapsed");

                    b.Property<string>("FunctionName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("FunctionName");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Ip");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Message");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("NickName");

                    b.Property<string>("OperationSystem")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("OperationSystem");

                    b.Property<int>("ResultType")
                        .HasColumnType("int")
                        .HasComment("ResultType");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("UserAgent");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("UserId");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("UserName");

                    b.HasKey("Id");

                    b.ToTable("Systems_AuditOperation", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Systems.Entities.AuditProperty", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AuditEntityId")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");

                    b.Property<Guid>("AuditEntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("AuditEntityId");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("DataType");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("DisplayName");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("FieldName");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("NewValue");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("OriginalValue");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntityId");

                    b.ToTable("Systems_AuditProperty", (string)null);
                });

            modelBuilder.Entity("OSharp.Authorization.EntityInfos.EntityInfo", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("AuditEnabled")
                        .HasColumnType("bit")
                        .HasComment("是否数据审计");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("实体名称");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("PropertyJson")
                        .IsRequired()
                        .HasMaxLength(5000)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(max)");
========
                        .HasColumnType("nvarchar(max)")
                        .HasComment("实体属性信息Json字符串");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(500)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(500)");
========
                        .HasColumnType("nvarchar(500)")
                        .HasComment("实体类型名称");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("ClassFullNameIndex");

                    b.ToTable("Auth_EntityInfo", (string)null);
                });

            modelBuilder.Entity("OSharp.Authorization.Functions.Function", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<int>("AccessType")
                        .HasColumnType("int")
                        .HasComment("访问类型");

                    b.Property<string>("Action")
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("功能");

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("区域");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("AuditEntityEnabled")
                        .HasColumnType("bit")
                        .HasComment("是否数据审计");

                    b.Property<bool>("AuditOperationEnabled")
                        .HasColumnType("bit")
                        .HasComment("是否操作审计");

                    b.Property<int>("CacheExpirationSeconds")
                        .HasColumnType("int")
                        .HasComment("数据缓存秒数");

                    b.Property<string>("Controller")
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("控制器");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("IsAccessTypeChanged")
                        .HasColumnType("bit")
                        .HasComment("访问类型是否更改");

                    b.Property<bool>("IsAjax")
                        .HasColumnType("bit")
                        .HasComment("是否Ajax功能");

                    b.Property<bool>("IsCacheSliding")
                        .HasColumnType("bit")
                        .HasComment("是否相对过期时间");

                    b.Property<bool>("IsController")
                        .HasColumnType("bit")
                        .HasComment("是否控制器");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

                    b.Property<bool>("IsSlaveDatabase")
                        .HasColumnType("bit")
                        .HasComment("是否从库");

                    b.Property<bool>("IsSlaveDatabase")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(200)");
========
                        .HasColumnType("nvarchar(200)")
                        .HasComment("名称");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("Area", "Controller", "Action")
                        .IsUnique()
                        .HasDatabaseName("AreaControllerActionIndex")
                        .HasFilter("[Area] IS NOT NULL AND [Controller] IS NOT NULL AND [Action] IS NOT NULL");

                    b.ToTable("Auth_Function", (string)null);
                });

            modelBuilder.Entity("OSharp.Core.Systems.KeyValue", b =>
                {
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Display")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
========
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("编号");

                    b.Property<string>("Display")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("显示名称");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasComment("是否锁定");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
<<<<<<<< HEAD:samples/web/Liuliu.Demo.Web/Migrations/20221116015548_Init.Designer.cs
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValueJson")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");
========
                        .HasColumnType("nvarchar(512)")
                        .HasComment("数据键名");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasComment("Order");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("显示名称");

                    b.Property<string>("ValueJson")
                        .HasColumnType("text")
                        .HasComment("数据值JSON");

                    b.Property<string>("ValueType")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("数据值类型名");
>>>>>>>> master:samples/web/Liuliu.Demo.Web/Migrations/20250303081408_init.Designer.cs

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("KeyIndex");

                    b.ToTable("Systems_KeyValue", (string)null);
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.EntityRole", b =>
                {
                    b.HasOne("OSharp.Authorization.EntityInfos.EntityInfo", "EntityInfo")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Identity.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityInfo");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.EntityUser", b =>
                {
                    b.HasOne("OSharp.Authorization.EntityInfos.EntityInfo", "EntityInfo")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.Module", b =>
                {
                    b.HasOne("Liuliu.Demo.Authorization.Entities.Module", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.ModuleFunction", b =>
                {
                    b.HasOne("OSharp.Authorization.Functions.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Authorization.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.ModuleRole", b =>
                {
                    b.HasOne("Liuliu.Demo.Authorization.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Identity.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.ModuleUser", b =>
                {
                    b.HasOne("Liuliu.Demo.Authorization.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.LoginLog", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.Organization", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.Role", b =>
                {
                    b.HasOne("Liuliu.Demo.Infos.Entities.Message", null)
                        .WithMany("PublicRoles")
                        .HasForeignKey("MessageId");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.RoleClaim", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.User", b =>
                {
                    b.HasOne("Liuliu.Demo.Infos.Entities.Message", null)
                        .WithMany("Recipients")
                        .HasForeignKey("MessageId");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserClaim", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserDetail", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("Liuliu.Demo.Identity.Entities.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserLogin", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserRole", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.UserToken", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.Message", b =>
                {
                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.MessageReceive", b =>
                {
                    b.HasOne("Liuliu.Demo.Infos.Entities.Message", "Message")
                        .WithMany("Receives")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.MessageReply", b =>
                {
                    b.HasOne("Liuliu.Demo.Infos.Entities.Message", "BelongMessage")
                        .WithMany()
                        .HasForeignKey("BelongMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Infos.Entities.Message", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Infos.Entities.MessageReply", "ParentReply")
                        .WithMany("Replies")
                        .HasForeignKey("ParentReplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liuliu.Demo.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BelongMessage");

                    b.Navigation("ParentMessage");

                    b.Navigation("ParentReply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Liuliu.Demo.Systems.Entities.AuditEntity", b =>
                {
                    b.HasOne("Liuliu.Demo.Systems.Entities.AuditOperation", "Operation")
                        .WithMany("AuditEntities")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Liuliu.Demo.Systems.Entities.AuditProperty", b =>
                {
                    b.HasOne("Liuliu.Demo.Systems.Entities.AuditEntity", "AuditEntity")
                        .WithMany("Properties")
                        .HasForeignKey("AuditEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEntity");
                });

            modelBuilder.Entity("Liuliu.Demo.Authorization.Entities.Module", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Liuliu.Demo.Identity.Entities.User", b =>
                {
                    b.Navigation("UserClaims");

                    b.Navigation("UserDetail");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.Message", b =>
                {
                    b.Navigation("PublicRoles");

                    b.Navigation("Receives");

                    b.Navigation("Recipients");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Liuliu.Demo.Infos.Entities.MessageReply", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Liuliu.Demo.Systems.Entities.AuditEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Liuliu.Demo.Systems.Entities.AuditOperation", b =>
                {
                    b.Navigation("AuditEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
