// <autogenerated>
//   This file was generated by T4 code generator ModelCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

// -----------------------------------------------------------------------
//  <copyright file="UserDetailConfiguration.generated.cs" company="OSharp开源团队">
//      Copyright (c) 2015 OSHARP. All rights reserved.
//  </copyright>
//  <site>http://www.osharp.org</site>
//  <last-editor>郭明锋</last-editor>
//  <last-date>2017-09-10 23:35</last-date>
// -----------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OSharp.Entity;

using OSharp.Demo.Identity.Entities;


namespace OSharp.Demo.EntityConfiguration.Identity
{
    /// <summary>
    /// 实体类-数据表映射——OSharp.Demo.Identity.Entities.UserDetail
    /// </summary> 
	public partial class UserDetailConfiguration : EntityTypeConfigurationBase<UserDetail, int>
    {        
        /// <summary>
        /// 重写以实现实体类型各个属性的数据库配置
        /// </summary>
        /// <param name="builder">实体类型创建器</param>
        public override void Configure(EntityTypeBuilder<UserDetail> builder)
        {
			UserDetailConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void UserDetailConfigurationAppend();
    }
}
